version: '2'

volumes:
  nodered-data:

services:
  rise-nodered:
    build: ./nodered
    restart: always
    ports:
      - '80:1880'
    volumes:
      - 'nodered-data:/usr/src/node-red/data'

  rise-gateway:
    build: ./gateway
    restart: always
    volumes:
      - '/dev:/dev:ro'