version: '2'

volumes:
  nodered-data:

services:
  rise-nodered:
    build: ./nodered
    environment: 
      LOG_LEVEL: ${LOG_LEVEL}
      ADMIN_USER: ${NODE_RED_USER}
      ADMIN_PWD: ${ENCRYPTED_PASSWORD}
    restart: always
    ports:
      - '80:1880'
    volumes:
      - 'nodered-data:/usr/src/node-red/data'

  # rise-ttn:
  #   build: ./ttn
  #   environment: 
  #     GW_ID: ${TTN_GW_ID}
  #     GW_KEY: ${TTN_GW_KEY}
  #     GW_RESET_PIN: ${TTN_GW_RESET_PIN}
  #   restart: always