version: '2'

volumes:
  nodered-data:

services:
  rise-nodered:
    build: ./nodered
    restart: always
    ports:
      - '80:1880'
    volumes:
      - 'nodered-data:/usr/src/node-red/data'

  rise-ttn:
    build: ./ttn
    restart: always