version: '2'

services:
  rise-nodered:
    environment:
      - NODE_RED_USER=${NODE_RED_USER}
      - NODE_RED_PASSWORD=${NODE_RED_PASSWORD}
      - NODE_RED_PLAIN_PASSWORD=${NODE_RED_PLAIN_PASSWORD}
      - LOG_LEVEL=${LOG_LEVEL}
      - RESIN_SUPERVISOR_ADDRESS=${RESIN_SUPERVISOR_ADDRESS}
      - RESIN_SUPERVISOR_API_KEY=${RESIN_SUPERVISOR_API_KEY}

  rise-gateway:
    environment:
      - GW_ID=${GW_ID}
      - GW_KEY=${GW_KEY}
      - GW_RESET_PIN=${GW_RESET_PIN}

  # rise-host:
  #   environment:
  #     - HOST_PORTS=22,23,80,48484
  
  # rise-node:
  #   build: ./node
  #   restart: always
  #   privileged: true
  #   ports:
  #     - "9991:80"
  
  rise-simple:
    build: ./simple
    restart: always
    privileged: true
    ports:
      - "9999:5000"

  # rise-host:
  #   build: ./host
  #   cap_add: ["NET_ADMIN", "NET_RAW"]
  #   mem_limit: 4M
  #   restart: always
  #   network_mode: host

  # dummy:
  #   image: bash
  #   command: ["ping", "rise-host"]
  #   depends_on:
  #     - rise-host
