version: '2'

services:
  rise-nodered:
    environment:
      - NODE_RED_USER=${NODE_RED_USER}
      - NODE_RED_PASSWORD=${NODE_RED_PASSWORD}
      - NODE_RED_PLAIN_PASSWORD=${NODE_RED_PLAIN_PASSWORD}
      - LOG_LEVEL=${LOG_LEVEL}
      - RESIN_SUPERVISOR_ADDRESS=${RESIN_SUPERVISOR_ADDRESS}
      - RESIN_SUPERVISOR_API_KEY=${RESIN_SUPERVISOR_API_KEY}

  rise-gateway:
    environment:
      - GW_ID=${GW_ID}
      - GW_KEY=${GW_KEY}
      - GW_RESET_PIN=${GW_RESET_PIN}

  # rise-usb:
  #   build: ./usbreset
  #   restart: always
  #   privileged: true
  #   devices:
  #     - "/dev/bus/usb/:/dev/bus/usb/"
  #   environment:
  #     - USB_VENDOR_ID=0951
  #     - USB_VENDOR_PRODUCT=1642
  
  # rise-python:
  #   build: ./python
  #   restart: always
  #   privileged: true
  #   ports:
  #     - "9999:5000"

  # rise-host:
  #   build: ./host
  #   cap_add: ["NET_ADMIN", "NET_RAW"]
  #   mem_limit: 4M
  #   restart: always
  #   network_mode: host

  # dummy:
  #   image: bash
  #   command: ["ping", "rise-host"]
  #   depends_on:
  #     - rise-host
