version: '2'

services:
  rise-nodered:
    build: ./nodered
    environment: 
      LOG_LEVEL: info
      ADMIN_USER: ${NODE_RED_USER}
      ADMIN_PWD: ${NODE_RED_ENCRYPTED_PASSWORD}
    restart: always
    ports:
      - '80:1880'

  # rise-ttn:
  #   build: ./ttn
  #   environment: 
  #     GW_ID: ${TTN_GW_ID}
  #     GW_KEY: ${TTN_GW_KEY}
  #     GW_RESET_PIN: ${TTN_GW_RESET_PIN}
  #   restart: always