version: "2"

volumes:
  nodered-data:

services:
  rise-nodered:
    build: ./nodered
    restart: always
    privileged: true
    ports:
      - "80:1880"
    volumes:
      - "nodered-data:/data"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/ttyUSB1:/dev/ttyUSB1"
      - "/dev/ttyUSB3:/dev/ttyUSB3"
      - "/dev/ttyUSB4:/dev/ttyUSB4"
      - "/dev/ttyS0:/dev/ttyS0"
      - "/dev/ttyAMA0:/dev/ttyAMA0"
      - "/dev/bus/usb/:/dev/bus/usb/"
    cap_add:
      - SYS_RAWIO
    labels:
      io.resin.features.kernel-modules: "1"
      io.resin.features.firmware: "1"
      io.resin.features.dbus: "1"
      io.resin.features.supervisor-api: "1"

  rise-gateway:
    build: ./gateway
    restart: always
    privileged: true
    devices:
      - "/dev/mem:/dev/mem"
    cap_add:
      - SYS_RAWIO

  rise-node:
    build: ./node
    restart: always
    privileged: true
    ports:
      - "1111:80"